### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by SherlockHolmes221** [jhcho99/gsrtr#1]
How to test on the whole dataset and get the final results in the paper? Thanks

**Comment by jhcho99** [comment]
You can get evaluation results on the **dev** set with the saved model:
```
python main.py --saved_model gsrtr_checkpoint.pth --output_dir gsrtr --dev
```

Similarly, you can get evaluation results on the **test** set with the saved model:
```
python main.py --saved_model gsrtr_checkpoint.pth --output_dir gsrtr --test
```

Our repository contains the saved model `gsrtr_checkpoint.pth`, and you can download it.
The saved model is not exactly the same model used in our paper, but it would show similar results with the reported results in our paper. 

Thanks for your interest in our paper and repository!!

**Comment by jhcho99** [comment]
Please reopen this issue whenever you need any help regarding this issue.
